import { randomUUID } from "node:crypto";
import { extname } from "node:path";

/**
 * Where uploaded bytes go, behind one interface.
 *
 * THE STORAGE DECISION, STATED. Assessment 12 puts user uploads in object
 * storage (S3 / MinIO / Spaces). Today they sit on the web server's disk. This
 * ships the disk, because that is what the business already runs and it needs no
 * new infrastructure, no credentials and no bucket policy to review — but it
 * ships it BEHIND THIS INTERFACE, so moving to object storage is one new class
 * and one line in `storage.module.ts`, not a change to any caller.
 *
 * Nothing above this interface knows there is a filesystem. Repositories hold a
 * `storageKey` string and never a path.
 *
 * WHAT THIS FIXES, from 08-Security-Model-and-Review.md:
 *
 *   H-9  Unrestricted file upload — no extension, size or content-type check,
 *        written into `wwwroot/` and served directly from the web root.
 *   H-10 Path traversal in the inward document handler
 *        (`ItemInWordController.cs:181`).
 *
 * The legacy single-file path is worth reading once, because every mistake
 * available is in four lines:
 *
 *     var path = Environment.WebRootPath;
 *     var filepath = "Content/InWordDocument/" + ItemInWordDetails.DocumentName.FileName;
 *     var fullpath = Path.Combine(path, filepath);
 *     UploadFile(ItemInWordDetails.DocumentName, fullpath);
 *
 *  1. `FileName` is the browser's, unsanitised. It may contain path separators
 *     and `..`, so the destination is caller-controlled — an arbitrary file
 *     WRITE anywhere the web process can reach, `appsettings.json` included.
 *  2. `FileMode.Create` truncates. Two suppliers uploading `invoice.pdf`
 *     silently overwrite one another; the second challan then shows the first's
 *     document. (The multi-file paths prefix a GUID and avoid this. The
 *     single-file one does not, and both are live.)
 *  3. Inside `wwwroot`, so every file is anonymously downloadable by anyone who
 *     guesses a name. No login, no permission, no site scope.
 *  4. No extension, size or type check, so an `.html` upload is stored XSS on
 *     the application's own origin.
 *
 * Every one of those is a property of WHERE and HOW the bytes were written, so
 * every one is answered here rather than in a controller:
 *
 *  - the key is generated by `newStorageKey`, never derived from user input;
 *  - a driver must re-verify the resolved location is inside its root anyway;
 *  - the root is outside anything a web server serves;
 *  - the file name the user chose is DATA on the row, not part of the path.
 */

/** Opaque to every caller. Only the driver may interpret it. */
export type StorageKey = string;

export interface StoredObject {
  key: StorageKey;
  sizeBytes: number;
}

export interface DocumentStorage {
  /** Writes bytes and returns the key they can be read back with. */
  put(key: StorageKey, bytes: Buffer): Promise<StoredObject>;
  get(key: StorageKey): Promise<Buffer>;
  /** Removing something already gone is not an error — deletes must be re-runnable. */
  remove(key: StorageKey): Promise<void>;
  exists(key: StorageKey): Promise<boolean>;
}

export const DOCUMENT_STORAGE = Symbol("DOCUMENT_STORAGE");

/** The bytes named by a key are missing, though a row still points at them. */
export class StoredObjectMissingError extends Error {
  constructor(readonly key: StorageKey) {
    super(`Stored object not found: ${key}`);
    this.name = "StoredObjectMissingError";
  }
}

/**
 * A key is `<prefix>/<uuid><ext>`, and the only user-derived part is the
 * EXTENSION — filtered to a short allowlisted token before it gets here.
 *
 * The uploaded file name is never in the key. It is kept on the row, shown in
 * the UI and used for the download's `Content-Disposition`, which is the only
 * place it can do no harm.
 */
export function newStorageKey(prefix: string, fileName: string): StorageKey {
  const extension = safeExtension(fileName);
  return `${prefix}/${randomUUID()}${extension}`;
}

/**
 * The extension, if it is plausibly one, and "" otherwise.
 *
 * Deliberately strict: letters and digits, at most eight of them. It is a hint
 * for a human copying the file out, and it must not be able to reintroduce a
 * separator, a `..` or a second extension into a key.
 */
export function safeExtension(fileName: string): string {
  const extension = extname(fileName).toLowerCase();
  return /^\.[a-z0-9]{1,8}$/.test(extension) ? extension : "";
}

/**
 * The base name of an uploaded file, with every directory component removed.
 *
 * `basename()` alone is not enough: it is platform-aware, so on Linux it treats
 * a Windows path as one long file name and `C:\evil\..\x.pdf` survives intact.
 * Both separators are cut here regardless of platform, because the name arrives
 * from a browser and not from this machine.
 */
export function safeFileName(fileName: string, fallback = "attachment"): string {
  const base = fileName
    .split(/[\\/]/)
    .pop()
    // Control characters render as nothing and can hide a name's real ending.
    // eslint-disable-next-line no-control-regex
    ?.replace(/[\u0000-\u001f\u007f]/g, "")
    .trim();

  if (!base || base === "." || base === "..") {
    return fallback;
  }
  return base.slice(0, 255);
}
