import { mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, join, resolve, sep } from "node:path";
import { Injectable } from "@nestjs/common";
import {
  StoredObjectMissingError,
  type DocumentStorage,
  type StorageKey,
  type StoredObject,
} from "./document-storage";

/**
 * Files on this machine's disk, under one root.
 *
 * The root is a directory the web server does not serve. On the VPS that is
 * `/opt/accountbook-next/uploads` — NOT inside `releases/<timestamp>/`, which
 * `current` points at and which the deploy prunes to the last five. Uploads
 * written into a release directory would be deleted by the fifth deploy after
 * they were made, and nothing would report it until someone asked for the file.
 *
 * Swapping this for S3 is a class with the same four methods.
 */
@Injectable()
export class LocalDiskStorage implements DocumentStorage {
  private readonly root: string;

  constructor(root: string) {
    this.root = resolve(root);
  }

  /**
   * Resolves a key to a path and REFUSES anything that escapes the root.
   *
   * Keys are generated by `newStorageKey` and cannot contain a traversal, so in
   * normal operation this can never fire. It is here anyway, because the check
   * that never fires is the one that matters the day a key arrives from the ETL,
   * a fixture or a future caller that skipped the generator — which is precisely
   * how H-10 happened: the old handler trusted its input to be a file name.
   *
   * `startsWith(root)` alone is wrong — `/opt/uploads-evil` starts with
   * `/opt/uploads`. The separator is part of the comparison.
   */
  private pathFor(key: StorageKey): string {
    if (key === "" || isAbsolute(key) || key.includes("\0")) {
      throw new Error(`Unsafe storage key: ${JSON.stringify(key)}`);
    }

    const full = resolve(join(this.root, key));
    if (full !== this.root && !full.startsWith(this.root + sep)) {
      throw new Error(`Storage key escapes the storage root: ${JSON.stringify(key)}`);
    }
    return full;
  }

  async put(key: StorageKey, bytes: Buffer): Promise<StoredObject> {
    const path = this.pathFor(key);
    await mkdir(dirname(path), { recursive: true });
    // "wx" — fail if it exists. Keys carry a UUID so a collision means a bug,
    // and the legacy `FileMode.Create` silently overwriting one supplier's
    // invoice with another's is the reason this refuses rather than truncates.
    await writeFile(path, bytes, { flag: "wx" });
    return { key, sizeBytes: bytes.byteLength };
  }

  async get(key: StorageKey): Promise<Buffer> {
    try {
      return await readFile(this.pathFor(key));
    } catch (error) {
      if (isMissing(error)) {
        throw new StoredObjectMissingError(key);
      }
      throw error;
    }
  }

  /** Idempotent: a delete that has already happened is a success. */
  async remove(key: StorageKey): Promise<void> {
    await rm(this.pathFor(key), { force: true });
  }

  async exists(key: StorageKey): Promise<boolean> {
    try {
      const info = await stat(this.pathFor(key));
      return info.isFile();
    } catch (error) {
      if (isMissing(error)) {
        return false;
      }
      throw error;
    }
  }

  /**
   * Creates the root and proves it is writable, at BOOT.
   *
   * A storage directory that is missing or read-only otherwise surfaces as a 500
   * on someone's first upload, long after the deploy that caused it.
   */
  async verifyWritable(): Promise<void> {
    await mkdir(this.root, { recursive: true });
    const probe = join(this.root, `.write-probe-${process.pid}`);
    try {
      await writeFile(probe, "");
    } catch (error) {
      throw new Error(
        `Storage directory is not writable: ${this.root}\n` +
          `  ${error instanceof Error ? error.message : String(error)}\n` +
          "  Set STORAGE_DIR to a directory the service user can write to.",
      );
    } finally {
      await rm(probe, { force: true });
    }
  }
}

const isMissing = (error: unknown): boolean =>
  typeof error === "object" && error !== null && (error as { code?: string }).code === "ENOENT";
