CREATE TABLE "items" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"unit_id" integer NOT NULL,
	"price_per_unit" numeric(18, 2) NOT NULL,
	"is_with_gst" boolean DEFAULT false NOT NULL,
	"gst_percent" numeric(5, 2),
	"gst_amount" numeric(18, 2),
	"hsn_code" text,
	"is_approved" boolean DEFAULT false NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" uuid,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "suppliers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"mobile" text,
	"email" text,
	"gst_no" text,
	"building_name" text,
	"area" text NOT NULL,
	"city_id" integer,
	"state_id" integer,
	"pincode" text,
	"bank_name" text,
	"bank_branch" text,
	"account_no" text,
	"ifsc_code" text,
	"is_approved" boolean DEFAULT false NOT NULL,
	"opening_balance" numeric(18, 2),
	"opening_balance_date" timestamp with time zone,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" uuid,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "units" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "units_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" uuid,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "items" ADD CONSTRAINT "items_unit_id_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."units"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "items_name_lower_key" ON "items" USING btree (lower("name")) WHERE "items"."is_deleted" = false;--> statement-breakpoint
CREATE INDEX "items_unit_id_idx" ON "items" USING btree ("unit_id");--> statement-breakpoint
CREATE UNIQUE INDEX "suppliers_gst_no_key" ON "suppliers" USING btree (upper("gst_no")) WHERE "suppliers"."gst_no" is not null and "suppliers"."is_deleted" = false;--> statement-breakpoint
CREATE UNIQUE INDEX "suppliers_name_lower_key" ON "suppliers" USING btree (lower("name")) WHERE "suppliers"."is_deleted" = false;--> statement-breakpoint
CREATE INDEX "suppliers_is_approved_idx" ON "suppliers" USING btree ("is_approved");--> statement-breakpoint
CREATE UNIQUE INDEX "units_name_lower_key" ON "units" USING btree (lower("name"));