-- Agency Master (client request, 1 Oct 2026): the contractors who work on a
-- site, the trades they do, and the people to call.
--
-- HAND-TRIMMED. `drizzle-kit generate` also emitted 0020's three statements on
-- `site_locations` (drop index, add `address`, re-create the index), because
-- 0020 was hand-written and has no snapshot — so the diff ran against 0019.
-- Those are applied on production already and would fail there. Removed; the
-- snapshot generated alongside this file is kept, which repairs the chain.
CREATE TABLE "agencies" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"address" text,
	"state_id" integer NOT NULL,
	"city_id" integer NOT NULL,
	"gst_no" text,
	"pan_no" text,
	"bank_name" text,
	"account_no" text,
	"ifsc_code" text,
	"account_holder_name" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" uuid,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "agency_contacts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"agency_id" uuid NOT NULL,
	"name" text NOT NULL,
	"designation" text,
	"mobile" text,
	"email" text,
	"line_number" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "agency_work_types" (
	"agency_id" uuid NOT NULL,
	"work_type_id" integer NOT NULL,
	CONSTRAINT "agency_work_types_agency_id_work_type_id_pk" PRIMARY KEY("agency_id","work_type_id")
);
--> statement-breakpoint
CREATE TABLE "work_types" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "work_types_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "agencies" ADD CONSTRAINT "agencies_state_id_states_id_fk" FOREIGN KEY ("state_id") REFERENCES "public"."states"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agencies" ADD CONSTRAINT "agencies_city_id_cities_id_fk" FOREIGN KEY ("city_id") REFERENCES "public"."cities"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agency_contacts" ADD CONSTRAINT "agency_contacts_agency_id_agencies_id_fk" FOREIGN KEY ("agency_id") REFERENCES "public"."agencies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agency_work_types" ADD CONSTRAINT "agency_work_types_agency_id_agencies_id_fk" FOREIGN KEY ("agency_id") REFERENCES "public"."agencies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agency_work_types" ADD CONSTRAINT "agency_work_types_work_type_id_work_types_id_fk" FOREIGN KEY ("work_type_id") REFERENCES "public"."work_types"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "agencies_city_id_idx" ON "agencies" USING btree ("city_id");--> statement-breakpoint
CREATE UNIQUE INDEX "agencies_name_lower_key" ON "agencies" USING btree (lower("name")) WHERE "agencies"."is_deleted" = false;--> statement-breakpoint
CREATE INDEX "agency_contacts_agency_id_idx" ON "agency_contacts" USING btree ("agency_id");--> statement-breakpoint
CREATE INDEX "agency_work_types_work_type_id_idx" ON "agency_work_types" USING btree ("work_type_id");--> statement-breakpoint
CREATE UNIQUE INDEX "work_types_name_lower_key" ON "work_types" USING btree (lower("name"));--> statement-breakpoint
-- The trades named in the client's mockup, so the form has something to pick
-- on day one. More are added from the agency form.
INSERT INTO "work_types" ("name") VALUES
	('Civil Work'), ('RCC'), ('Masonry'), ('Plaster'), ('Shuttering'), ('Steel Work'),
	('Flooring'), ('Tiles'), ('Marble'), ('Waterproofing'), ('Chemical'),
	('Electrical'), ('HVAC'), ('Plumbing'), ('Sanitary'), ('Painting'), ('Colour'),
	('Texture'), ('Finishing')
ON CONFLICT DO NOTHING;
--> statement-breakpoint
-- The right to manage agencies: form row "Agency", so the subject is `agency`.
-- Id 101, beside 0018's 100, clear of the legacy ids (1-29) and the dev seed's.
INSERT INTO "forms" ("id", "form_group", "form_name", "controller", "order_id", "is_active")
VALUES (101, 'Masters', 'Agency', NULL, 101, true)
ON CONFLICT ("id") DO NOTHING;
--> statement-breakpoint
-- Granted to whoever may already edit suppliers — the nearest existing master.
-- Anyone else is granted it on the Permissions screen, like any other form.
INSERT INTO "user_form_permissions" ("user_id", "form_id", "is_view_allow", "is_add_allow", "is_edit_allow", "is_delete_allow", "is_approved")
SELECT DISTINCT p."user_id", 101, true, true, true, true, false
FROM "user_form_permissions" p
JOIN "forms" f ON f."id" = p."form_id"
WHERE f."form_name" = 'Supplier' AND f."is_active" AND p."is_edit_allow"
ON CONFLICT DO NOTHING;
