-- Payout lists (client request, 5 Oct 2026): a saved plan of which suppliers to pay
-- and how much of each. A plan only; nothing here touches payments.
--
-- Generated by drizzle-kit and checked: only the two new tables and the permission
-- rows below, no stray statements from earlier migrations.
CREATE TABLE "payout_list_lines" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"payout_list_id" uuid NOT NULL,
	"party_id" uuid NOT NULL,
	"amount" numeric(18, 2) NOT NULL,
	"outstanding_at_save" numeric(18, 2),
	"line_number" integer NOT NULL,
	CONSTRAINT "payout_list_lines_list_party_key" UNIQUE("payout_list_id","party_id"),
	CONSTRAINT "payout_list_lines_amount_positive" CHECK ("payout_list_lines"."amount" > 0)
);
--> statement-breakpoint
CREATE TABLE "payout_lists" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"list_date" date NOT NULL,
	"title" text,
	"budget" numeric(18, 2),
	"note" text,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" uuid,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "payout_list_lines" ADD CONSTRAINT "payout_list_lines_payout_list_id_payout_lists_id_fk" FOREIGN KEY ("payout_list_id") REFERENCES "public"."payout_lists"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payout_list_lines" ADD CONSTRAINT "payout_list_lines_party_id_suppliers_id_fk" FOREIGN KEY ("party_id") REFERENCES "public"."suppliers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "payout_list_lines_payout_list_id_idx" ON "payout_list_lines" USING btree ("payout_list_id");--> statement-breakpoint
CREATE INDEX "payout_lists_list_date_idx" ON "payout_lists" USING btree ("list_date" desc) WHERE "payout_lists"."is_deleted" = false;--> statement-breakpoint
-- The right to keep payout lists: form row "Payout", so the subject is `payout`.
-- Id 102, beside 100 and 101, clear of the legacy ids (1-29) and the dev seed's.
-- Grouped with the reports, which is where the screen sits beside the payout summary.
INSERT INTO "forms" ("id", "form_group", "form_name", "controller", "order_id", "is_active")
VALUES (102, 'Reports', 'Payout', NULL, 102, true)
ON CONFLICT ("id") DO NOTHING;
--> statement-breakpoint
-- Granted to whoever already holds Reports & Payments, flag for flag: the list
-- shows party outstanding, so it goes to the people who could already see it.
-- A user with two such rows (a live and a retired one) gets the union of their
-- flags, once. A row without view is skipped — it carries no right to the
-- screen. Approve is never copied; a list has no approval.
INSERT INTO "user_form_permissions" ("user_id", "form_id", "is_view_allow", "is_add_allow", "is_edit_allow", "is_delete_allow", "is_approved")
SELECT p."user_id", 102, true, bool_or(p."is_add_allow"), bool_or(p."is_edit_allow"), bool_or(p."is_delete_allow"), false
FROM "user_form_permissions" p
JOIN "forms" f ON f."id" = p."form_id"
WHERE f."form_name" = 'Reports & Payments' AND f."is_active" AND p."is_view_allow"
GROUP BY p."user_id"
ON CONFLICT DO NOTHING;
